### PR TITLE
chapter 6

### PR DESCRIPTION
**Pull request by defuneste**
chapter 6 and chapter 6 pkg dependencies update

### CODE REVIEW

**Review by jonthegeek — DISMISSED** [review]
Looks good as long as it builds!

**Comment by defuneste** [comment]
> Looks good as long as it builds!
Will it be better if I had more pkg in DESCRIPTION instead of building a "dependency tree" ?

**Comment by jonthegeek** [comment]
@defuneste This is the error:

```
label: inla
Quitting from lines 1673-1681 (bookclub-geohealth.Rmd) 
Error in inla.check.control(control.compute, data) : 
  Name `return.marginals.predictor' in control-argument `control.compute', is void.

  Valid ones are:
	config
	cpo
	dic
	gdensity
	graph
	hyperpar
	mlik
	openmp.strategy
	po
	q
	return.marginals
	smtp
	waic
Calls: <Anonymous> ... eval_with_user_handlers -> eval -> eval -> inla -> inla.check.control
```

I'll see if I can see exactly where/why that happens.

It doesn't look like this one is a dependency issue. Does it build locally for you?

**Comment by defuneste** [comment]
yes it builds I think this is in chapter 6 the R code chunk name inla
(L216). I will investigate it also a bit. I should setup myself a test
envt...

if you ?control.compute you can see that `return.marginals.predictor` is valid

**Comment by defuneste** [comment]
I can save `res` in RDS and read it later. It will be a 5.2 MB files.

**Comment by jonthegeek** [comment]
I had to reinstall INLA, and I noticed that my local devtools::install_dev_deps() call was missing the bioconductor packages... so hopefully this change will get it to work. At least it works for me locally now!

**Comment by defuneste** [comment]
Thx! it look like INLA is a dependency purgatory!

**Comment by jonthegeek** [comment]
Superseded by #20

**Pull request closed without merging**
