### PR TITLE
chap3

### PR DESCRIPTION
**Pull request by defuneste**
Ok this is chapter 3 lot of uncertainty on how INLA works, as I said I hope we can come back to this chapter later when we will have practice it!

### CODE REVIEW

**Review by jonthegeek — DISMISSED** [review]
Looks good as long as the renderer agrees!

**Comment by defuneste** [comment]
I am correcting the issue!

**Comment by defuneste** [comment]
Apparently we have not set pdflatex in the repo so the equations are not rendered, the ugly hack was loading them and calling them. Let see if it works. Sorry for the inconvenience ...

**Review by jonthegeek — APPROVED** [review]
Ok, for now the hack has to do, because I couldn't get this to build on my machine even with latex set up.

**Pull request merged**
